export const Users = [
    {
        id: 1,
        profilePicture: 'assets/person/1.jpeg',
        userName: 'Miss Hoover',
    },
    {
        id: 2,
        profilePicture: 'assets/person/2.jpeg',
        userName: 'Groundskeeper Willie',
    },
    {
        id: 3,
        profilePicture: 'assets/person/3.jpeg',
        userName: 'Grampa Simpson',
    },
    {
        id: 4,
        profilePicture: 'assets/person/4.jpeg',
        userName: 'Chief Wiggum',
    },
    {
        id: 5,
        profilePicture: 'assets/person/5.jpeg',
        userName: 'Dr. Hibbert',
    },
    {
        id: 6,
        profilePicture: 'assets/person/6.jpeg',
        userName: 'Lenny Leonard',
    },
    {
        id: 7,
        profilePicture: 'assets/person/7.jpeg',
        userName: 'Milhouse Van Houten',
    },
    {
        id: 8,
        profilePicture: 'assets/person/8.jpeg',
        userName: 'Allison Taylor',
    },
    {
        id: 9,
        profilePicture: 'assets/person/9.jpeg',
        userName: 'Selma Bouvier',
    },
    {
        id: 10,
        profilePicture: 'assets/person/10.jpeg',
        userName: 'Edna Krabappel',
    },
];

export const Posts = [
    {
        id: 1,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/1.jpeg',
        date: '5 mins ago',
        userId: 1,
        like: 32,
        comment: 6,
    },
    {
        id: 2,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/2.jpeg',
        date: '15 mins ago',
        userId: 2,
        like: 30,
        comment: 2,
    },
    {
        id: 3,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/3.jpeg',
        date: '25 mins ago',
        userId: 3,
        like: 22,
        comment: 16,
    },
    {
        id: 4,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/4.jpeg',
        date: 'an hour ago',
        userId: 4,
        like: 39,
        comment: 19,
    },
    {
        id: 5,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/5.jpeg',
        date: '2 hours ago',
        userId: 5,
        like: 37,
        comment: 14,
    },
    {
        id: 6,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/6.jpeg',
        date: '5 hours ago',
        userId: 6,
        like: 32,
        comment: 13,
    },
    {
        id: 7,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/7.jpeg',
        date: '7 hours ago',
        userId: 7,
        like: 34,
        comment: 8,
    },
    {
        id: 8,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/8.jpeg',
        date: '12 hours ago',
        userId: 8,
        like: 54,
        comment: 6,
    },
    {
        id: 9,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/9.jpeg',
        date: '14 hours ago',
        userId: 9,
        like: 52,
        comment: 12,
    },
    {
        id: 10,
        descr: 'Love for all, hatred for none',
        photo: 'assets/post/10.jpeg',
        date: 'yesterday',
        userId: 10,
        like: 43,
        comment: 3,
    },
];